//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COM_WindApplication.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.7.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F:\\Games\\ILYAsFolder\\BarSU\\LABS\\4_course\\EugineShapovich\\VisualKa\\VisualCLibSolut" +
            "ions\\COM\\COM_Application\\COM_WindApplication\\bin\\Debug\\doc\\DefaultTemplate.docx")]
        public string newTemplateDocPath {
            get {
                return ((string)(this["newTemplateDocPath"]));
            }
            set {
                this["newTemplateDocPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F:\\Games\\ILYAsFolder\\BarSU\\LABS\\4_course\\EugineShapovich\\VisualKa\\VisualCLibSolut" +
            "ions\\COM\\COM_Application\\COM_WindApplication\\bin\\Debug\\newdoc")]
        public string newDefaultFilePath {
            get {
                return ((string)(this["newDefaultFilePath"]));
            }
            set {
                this["newDefaultFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F:\\Games\\ILYAsFolder\\BarSU\\LABS\\4_course\\EugineShapovich\\VisualKa\\VisualCLibSolut" +
            "ions\\COM\\COM_Application\\COM_WindApplication\\bin\\Debug\\doc\\DemonstrateTemplate.d" +
            "ocx")]
        public string demoTemplate {
            get {
                return ((string)(this["demoTemplate"]));
            }
            set {
                this["demoTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool advanceSettings {
            get {
                return ((bool)(this["advanceSettings"]));
            }
            set {
                this["advanceSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool manualInput {
            get {
                return ((bool)(this["manualInput"]));
            }
            set {
                this["manualInput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F:\\Games\\ILYAsFolder\\BarSU\\LABS\\4_course\\EugineShapovich\\VisualKa\\VisualCLibSolut" +
            "ions\\COM\\COM_Application\\COM_WindApplication\\bin\\Debug\\doc\\DemonstrateTemplate.x" +
            "lsx")]
        public string demoExcelTemplate {
            get {
                return ((string)(this["demoExcelTemplate"]));
            }
            set {
                this["demoExcelTemplate"] = value;
            }
        }
    }
}
